version: '3.8'
 
services:
 
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql:latest 
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TraineeManagement
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:latest 
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
 
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
 
  trainingdirectory:
    image: directoryapi
    container_name: trainingdirectory
    build:
      context: ./TrainingDirectory.API
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5050:8080"
 
  traineemanagement-api:
    image: traineeapi
    container_name: trainee-api
    build:
      context: .
      dockerfile: TraineeManagement.Api/Dockerfile
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
 
  worker:
    image: workerapi
    container_name: trainee-worker
    build:
      context: .
      dockerfile: TraineeManagement.WORKER/Dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mysql_data:
